### ISSUE TITLE
Questions on Custom Fields

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-api-docs#102]
Some questions regarding Custom Fields:

1. Once created, where do these fields present themselves in the the user resources for reading, updating and deleting?
1. What characters can be used for the `displayName`? Is UTF-8 supported?
1. What is the maximum length of a custom field `displayName`?
1. What are the available data types of a custom field value?
1. What is the max length of a custom field value?
1. How do these fields interact with Account Federation? Do all fields need to bee the same across federated accounts or not?

Please include info in the docs.

Custom fields info:

* https://developers.ringcentral.com/guide/account/custom-fields
* https://developers.ringcentral.com/api-reference/Custom-Fields/createCustomField

**Comment by byrnereese** [comment]
Documentation has been updated. Some content being defined in the API reference.
