### ISSUE TITLE
Update Call Log JavaScript example code

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-api-docs#103]
Regarding the JavaScript example on this page:

* https://developers.ringcentral.com/guide/voice/call-log/reading-call-log
* https://github.com/ringcentral/ringcentral-api-docs/blob/master/docs/voice/call-log/reading-call-log.md

Please review this finding which indicates the URL for JavaScript should be updated from `/account/~/extension/~/call-log` to `/restapi/v1.0/account/~/extension/~/call-log`:

* https://stackoverflow.com/questions/60459763/getting-a-404-error-when-using-the-call-log-api

**Comment by byrnereese** [comment]
Fixed
