### ISSUE TITLE
Move API Spec-related content from DevGuide to API Docs

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-api-docs#11]
- [x] Review all content in Developer Guide [Overview](http://ringcentral-api-docs.readthedocs.io/en/latest/overview/) for viability of migration into API Reference
- [x]  Review all [API Rate Limits](http://ringcentral-api-docs.readthedocs.io/en/latest/rate_limits/) content and determine which content needs moved into the API Reference
- [x] Complete cursory review of Developer Guide for any remaining content which would improve the value and consistency of API Reference

**Comment by byrnereese** [comment]
Done.
