### ISSUE TITLE
Edit this page link busted for messaging getting started

### ISSUE THREAD

**Issue by adamd** [ringcentral/ringcentral-api-docs#120]
👋  Just noticed that [Getting Started with SMS](https://developers.ringcentral.com/guide/messaging/quick-start) "edit this page" link 404s ([links to here](https://github.com/ringcentral/ringcentral-api-docs/tree/master/docs/messaging/quick-start/index.md)). It looks like sometime since the last update in May it moved to a different location in the repo. @byrnereese may know more?

**Comment by byrnereese** [comment]
I think this was a transient issue. This is no longer reproducible.
