### ISSUE TITLE
Parameter [expiresIn] value is invalid

### ISSUE THREAD

**Issue by hambrise** [ringcentral/ringcentral-api-docs#14]
```js
{
  "errorCode": "InvalidParameter",
  "message": "Parameter [expiresIn] value is invalid",
  "errors": [
    {
      "errorCode": "CMN-101",
      "message": "Parameter [expiresIn] value is invalid",
      "parameterName": "expiresIn"
    }
  ],
  "parameterName": "expiresIn"
}
```

**Comment by hambrise** [comment]
I tired to create subscription with webhook, with "ExpiresIn":0 i get this error,
i tired with Api Test - https://developer.ringcentral.com/api-explorer/latest/index.html#/!/Push_Notifications/loadSubscriptionList 
i am getting the same error

**Comment by tylerlong** [comment]
You mentioned `"ExpiresIn":0`. 

`ExpiresIn` should be larger than 0.

**Comment by hambrise** [comment]
I tired 
I used "1000","6000",..and so on
Still i get error - in sandbox environment

**Comment by tylerlong** [comment]
This is not the right place to troubleshoot technical issues.

What SDK are you using? Please post this issue to the SDK's repository.

Please check the SDKs/libraries we have: https://github.com/ringcentral

If you are not using any of the SDKs we provide, please post you question to https://devcommunity.ringcentral.com/ringcentraldev

Please don't forget to include your code snippets. I cannot reproduce the issue without your code snippets

**Comment by byrnereese** [comment]
This is a support request. Not a bug with documentation.
