### ISSUE TITLE
Response of interactivity in Adaptive Cards not working

### ISSUE THREAD

**Issue by Jokcy** [ringcentral/ringcentral-api-docs#178]
I followed [this doc](https://github.com/ringcentral/ringcentral-api-docs/blob/85675e38edd6ba3dfee65ceb7cd2dc881a56adc3/docs/team-messaging/adaptive-cards/actions.md) to handle interactivity in Adaptive Cards. I tried to response a message to tell the Ringcentral client need to notify user something, but nothing happened.

My code here:
```js
res.status(200).json({
     type: 'message',
     text: 'Token not valid',
});
```

What I expect is this should show a toast of the text.

I want to know if this should work, or how should I do to make this feature work.

**Comment by byrnereese** [comment]
@Jokcy what you did should work. We are investigating internally. Please stand-by.

**Comment by byrnereese** [comment]
We have since found that the documentation was in error. We have removed the incorrect documentation.
