### ISSUE TITLE
CI/CD fails with bad link error

### ISSUE THREAD

**Issue by suyashjoshi** [ringcentral/ringcentral-api-docs#186]
CI/CD failed with an error saying one bad link found but no description is given or I'm not understanding which link is broken, any idea ? See https://github.com/ringcentral/ringcentral-api-docs/runs/4562979861?check_suite_focus=true

**Comment by byrnereese** [comment]
If you look at the output of the logs in Github for the failed job, at the very end you will see a summary report. It outputs every page and the broken links found on that page. Look carefully and you will see it.

**Comment by byrnereese** [comment]
If you look at the output of the logs in Github for the failed job, at the very end you will see a summary report. It outputs every page and the broken links found on that page. Look carefully and you will see it.

**Comment by byrnereese** [comment]
Link checking has been moved put of github actions into an internal CI/CD system.
