### ISSUE TITLE
Don't hard code port number 4390

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-api-docs#19]
4390 is for botkit only I guess.

In the doc, we should make it a variable.   And tell user it should be the port number of local http service.

**Comment by byrnereese** [comment]
@tylerlong - (picking this ticket up after a loooooooong time) can you recommend a specific documentation change for this issue? Or cite for me a URL where this information would best reside?

**Comment by tylerlong** [comment]
Go to this page and search for 4390: https://github.com/ringcentral/ringcentral-api-docs/blob/master/docs/team-messaging/manual/local-bots.md

**Comment by byrnereese** [comment]
I believe this was fixed long ago.
