### ISSUE TITLE
Using phones in sandbox article references outdated software

### ISSUE THREAD

**Issue by faulky** [ringcentral/ringcentral-api-docs#195]
https://developers.ringcentral.com/guide/basics/your-rc-phone references the "RC Phone" app, but the instructions do not work for the new Ringcentral App.  Furthermore the link to download RC Phone is now broken

**Comment by CoCraig** [comment]
Thanks @faulky. I'll take a look at changing this.  We don't use RC Phone app for development anymore.  Please use this page to develop your integration in the new RingCentral App: https://developers.ringcentral.com/guide/basics/sandbox

**Comment by byrnereese** [comment]
Resolved by added clearer language about our support of RC Phone.
