### ISSUE TITLE
Glip message attachment API issues.

### ISSUE THREAD

**Issue by liugengyu** [ringcentral/ringcentral-api-docs#20]
https://medium.com/ringcentral-developers/announcing-enhanced-posting-with-glip-attachments-and-the-glip-file-upload-api-25e0ac5c72ce

## inconsistent message attachment format

WebHook and API has inconsistent attachment format.

## API doesn't support `title_link`

WebHook supports it. 

## Links posted in `attachments.fields.value`are escaped 

So it is actually unable to render links properly.
  
I only tested in with API. I didn't test WebHook.

**Comment by grokify** [comment]
## inconsistent message attachment format

This is a known issue and being addressed. They are similar but the goal is to have them be the same.

## Links posted in `attachments.fields.value`are escaped 

This works in the API using this example code:

https://github.com/grokify/go-ringcentral/blob/master/examples/glip_post_attachment/glip_post_attachment.go

**Comment by liugengyu** [comment]
## 3) Links posted in attachments.fields.valueare escaped

Only long fields have this issue. Short ones are OK.

I created a separate issue here: https://github.com/ringcentral/ringcentral-api-docs/issues/21

**Comment by grokify** [comment]
## 3) Links posted in attachments.fields.value are escaped

Also verified to not exist for Webhooks so only API for long fields.

**Comment by byrnereese** [comment]
This is now obsolete as the attachment system has been redesigned to use Adaptive Cards.
