### ISSUE TITLE
Links in Glip message attachment long fields don't work

### ISSUE THREAD

**Issue by liugengyu** [ringcentral/ringcentral-api-docs#21]
Sample attachment:

```js
    const attachments = [{
        type: 'Card',
        fields: [
          {
            title: 'title',
            value: '[test](http://google.com/hello/world) http://google.com/hello/world',
            style: 'Long'
          }
        ]
      })
    }]
```

Sample output:

![image](https://user-images.githubusercontent.com/35157141/34640747-8abb1d28-f333-11e7-9768-59c9dde48b96.png)

**Comment by liugengyu** [comment]
One more sample:

![image](https://user-images.githubusercontent.com/35157141/34640756-de17d43e-f333-11e7-9383-e202f858e3f2.png)

There are two links in the red rectangle, both of them are broken.

**Comment by grokify** [comment]
Verified for API, not an issue with inbound webhooks.

**Comment by zkebami** [comment]
i think thats the developer tried to fix an xss issue

**Comment by byrnereese** [comment]
This request is now obsolete with the use of Adaptive Cards.
