### ISSUE TITLE
Typo: iframUrl should be iframeURL

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-api-docs#221]
https://developers.ringcentral.com/guide/team-messaging/adaptive-cards/modal-dialogs

`iframeUrl ` should be changed to `iframeURL`, otherwise it simply doesn't work.

Working demo:

https://github.com/tylerlong/ringcentral-chatbot-dialog-demo/blob/main/src/express.ts#L38

**Comment by byrnereese** [comment]
Fixed. Thank you!
