### ISSUE TITLE
Add rate limit handling best practices documentation

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-api-docs#30]
The best way to handle rate limiting is along the lines of the following:

Simple single-threaded use case, e.g. downloading files serially:

* If you encounter a HTTP Response Header `X-Rate-Limit-Remaining` reaches `0` then wait the number of seconds defined in `X-Rate-Limit-Window` HTTP Response Header.
* If you encounter a HTTP Response Status code of `429` wait the number of seconds defined in the `Retry-After` HTTP Response header.

If `X-Rate-Limit-Remaining` is working properly, your app should never encounter a `429` error, which is desirable.

Server is overloaded.

* If you encounter a HTTP Response Header `503` wait a default amount of time and retry once. Alternately retry with exponential fallback like AWS SDK.

Allow configuration of:

* Default retry time
* Max number of retries

The `X-Rate-Limit-*` headers are discussed here:

* http://ringcentral-api-docs.readthedocs.io/en/latest/rate_limits/

Here is information on how SDKs handle exponential backoff:

https://docs.aws.amazon.com/general/latest/gr/api-retries.html

> In addition to simple retries, each AWS SDK implements exponential backoff algorithm for better flow control. The idea behind exponential backoff is to use progressively longer waits between retries for consecutive error responses. You should implement a maximum delay interval, as well as a maximum number of retries. The maximum delay interval and maximum number of retries are not necessarily fixed values, and should be set based on the operation being performed, as well as other local factors, such as network latency.
> 
> Most exponential backoff algorithms use jitter (randomized delay) to prevent successive collisions. Because you aren't trying to avoid such collisions in these cases, you don't need to use this random number. However, if you use concurrent clients, jitter can help your requests succeed faster. For more information, see the blog post for Exponential Backoff and Jitter.

**Comment by byrnereese** [comment]
Fixed. Thanks for the content!
