### ISSUE TITLE
More detail information for WebHook requirement

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-api-docs#37]
https://devcommunity.ringcentral.com/ringcentraldev/topics/sub-525-sandbox-webhook-subscription-failure?utm_source=notification&utm_medium=email&utm_campaign=new_comment&utm_content=reply_button&reply[id]=19553895#reply_19553895

> I think the documentation should be modified to let dev know that Ring Central request sends a header along with an empty body with content-type application-json. This will save additional time of unnecessary debugging.

**Comment by camilosilva** [comment]
Yes, I think this will help being more clear on what the expectations are when developing the initial webhook service accepting the call from RingCentral. Thanks!

**Comment by byrnereese** [comment]
Fixed
