### ISSUE TITLE
Use fictitious numbers for examples

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-api-docs#50]
To avoid people calling example numbers, use fictitious numbers for all examples.

In the `+1` country code for the North American Numbering Plan, use numbers from `555-0100` through `555-0199` which are specifically reserved for fictional use:

[https://en.wikipedia.org/wiki/555_(telephone_number)](https://en.wikipedia.org/wiki/555_(telephone_number))

**Comment by byrnereese** [comment]
Fixed
