### ISSUE TITLE
Fenced Code Blocks are  rendered incorrectly on the `bootstrap-vertical-nav` branch

### ISSUE THREAD

**Issue by vincent-cai** [ringcentral/ringcentral-api-docs#53]
### Problem

All fenced code blocks are not recognized by the `markdown-fenced-code-tabs` extension. They are displayed incorrectly as below screenshot:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/40990636/53795330-b78d0100-3f6c-11e9-9873-5a6e9521cc01.png">

### Solution

The root cause for this issue is that the label customization was used incorrectly (`tab="Request`):

```md
```http tab="Request"
POST /restapi/v1.0/account/~/extension/~/company-pager HTTP/1.1
Content-Type: application/json
Content-Length: ACTUAL_CONTENT_LENGTH_HERE

{
  "to": [{"extensionNumber": "102"}, 
         {"extensionNumber": "103"}],

  "from": {"extensionNumber": "101"},
  "text": "Hello!"
}

...
```

According to the [documentation](https://yacir.github.io/markdown-fenced-code-tabs/#label-customization) of `markdown-fenced-code-tabs` extension, to customize the tab label by passing the label to the `fct_label` argument. So the above code snippet should be:

```md
```http fct_label ="Request"
POST /restapi/v1.0/account/~/extension/~/company-pager HTTP/1.1
Content-Type: application/json
Content-Length: ACTUAL_CONTENT_LENGTH_HERE

{
  "to": [{"extensionNumber": "102"}, 
         {"extensionNumber": "103"}],

  "from": {"extensionNumber": "101"},
  "text": "Hello!"
}

...
```

After updated the label customization:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/40990636/53795519-1eaab580-3f6d-11e9-96cb-4295895755fb.png">

**Comment by vincent-cai** [comment]
I find there are two fenced code blocks extension are involved:

- [superfences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/)
- [markdown-fenced-code-tabs](https://github.com/yacir/markdown-fenced-code-tabs)

`markdown-fenced-code-tabs` was introduced in [this commit](https://github.com/ringcentral/ringcentral-api-docs/commit/eaebaf3720fb611dd8b9c681262f681a9c88bc1f) which causes this problem.

@byrnereese Could you please help to confirm/fix this issue by:

1. Using `superfences` and remove `markdown-fenced-code-tabs`
2. Or using `markdown-fenced-code-tabs` and update all docs that use `tab=` for label customization to `fct_label=`

**Comment by byrnereese** [comment]
Went with superfences. Thanks for the root cause analysis.
