### ISSUE TITLE
[voice/supervision-api.md] Ensure JSON examples parse and validate

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-api-docs#58]
The following example is missing an close `}` and does not validate. Please correct.

`{ "uri": "https://platform.ringcentral.com/restapi/v1.0/account/809646016/device/60727004", "id": "60727004", "type": "SoftPhone", "sku": "DV-1", "name": "Softphone - Digital Line", "serial": "LMRC8531", "computerName": "LMRC8531", "status": "Online", "extension": { "uri": "https://platform.ringcentral.com/restapi/v1.0/account/809646016/extension/809646016", "id": 809646016, "extensionNumber": "101" }`

**Comment by dibyenduroy** [comment]
Fixed in fork.

**Comment by grokify** [comment]
👍
