### ISSUE TITLE
[voice/supervision-api.md] Update to use JSON pretty formatting

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-api-docs#59]
For `voice/supervision-api.md` update the JSON examples to be pretty formatted using triple backticks instead of single backtick lines.

Various tools can do the formatting including the following webpage:

https://jsonformatter.curiousconcept.com/

Here's an example:

# Current

`{ "direction": "Outbound", "from": { "deviceId": "60727004", "extensionId": "809646016", "name": "Supervisor ABC", "phoneNumber": "101" }, "id": "party-4", "muted": false, "owner": { "accountId": "809646016", "extensionId": "809646016" }, "standAlone": false, "status": { "code": "Answered", "reason": "Supervising" }, "to": { "extensionId": "62226587016", "name": "Dibyendu Roy", "phoneNumber": "108" } }`

# Desired:

```json
{
  "direction":"Outbound",
  "from":{
    "deviceId":"60727004",
    "extensionId":"809646016",
    "name":"Supervisor ABC",
    "phoneNumber":"101"
  },
  "id":"party-4",
  "muted":false,
  "owner":{
    "accountId":"809646016",
    "extensionId":"809646016"
  },
  "standAlone":false,
  "status":{
    "code":"Answered",
    "reason":"Supervising"
  },
  "to":{
    "extensionId":"62226587016",
    "name":"Dibyendu Roy",
    "phoneNumber":"108"
  }
}
```

**Comment by dibyenduroy** [comment]
Resolved in fork.

**Comment by grokify** [comment]
🎉
