### ISSUE TITLE
Create quick start landing page per product for all languages

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-api-docs#65]
Please add a landing page for all the quick starts for a product. This way we can direct people to say the SMS Quick Starts without knowing what language they prefer ahead of time.

The use case would be to respond to a question like this where we don't know the user's language preference:

https://forums.developers.ringcentral.com/questions/2/how-do-i-send-an-sms.html

For example, we have the following today:

https://developers.ringcentral.com/guide/sms/quick-start/node

But it would be nice to have the following which provides an overview and a list of languages:

https://developers.ringcentral.com/guide/sms/quick-start

**Comment by byrnereese** [comment]
This has been resolved. See https://developers.ringcentral.com/guide/sms/quick-start
