### ISSUE TITLE
Unknown URI scheme for new app

### ISSUE THREAD

**Issue by glennmurley15** [ringcentral/ringcentral-api-docs#90]
Previously (according to specs here ringcentral-api-docs/docs/voice/uri-scheme.md, and also in the app I wrote), you could launch a call to RC Phone app, using the uri-scheme rcmobile://call?

However, I now have the updated version of Ring Central app, that I use daily, (yes, RC Phone is still installed on my phone)

When my app tries to make a call, obviously the uri-scheme rcmobile:// launches RC Phone.

What is the uri-scheme for Ring Central the app?

Thanks

**Comment by byrnereese** [comment]
This sounds like a support question, not a bug/issue with our documentation. Can I ask that you ask this question in our forums? https://forums.developers.ringcentral.com/
